[package]
name = "securipi"
version = "0.1.0"
authors = ["David Beaumont <david.beaumont@birdie.care>"]
edition = "2018"
license = "MIT"

[dependencies]
dotenv = "0.14.1"
twilio = "0.1.2"
rust_gpiozero = "0.2.1"
